# - name: helm-serve service
#   blockinfile:
#     path: /etc/systemd/system/helm-serve.service
#     create: yes
#     block: |
#       [Unit]
#       Description=Helm serve
#       After=network.target

#       [Service]
#       Type=simple
#       User=root
#       WorkingDirectory=/root
#       ExecStart=/usr/local/bin/helm serve
#       Restart=on-failure # or always, on-abort, etc

#       [Install]
#       WantedBy=multi-user.target
#   when: ansible_hostname == 'kube-master'
- hosts: kube-all[0]
  tasks:
    - name: copy RBAC for tiller
      copy:
        src: files/tiller-rbac-config.yaml
        dest: /root/tiller-rbac-config

    - name: install helm
      shell: |
        kubectl apply -f /root/tiller-rbac-config
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
        helm init --service-account tiller
