- hosts: ceph-all
  tasks:
    - name: add ceph apt key
      apt_key:
        url: https://download.ceph.com/keys/release.asc

    - name: add ceph repo
      apt_repository:
        repo: deb https://download.ceph.com/debian-luminous/ {{ ansible_distribution_release }} main
        state: present

    - name: install ceph-deploy
      apt: name=ceph-deploy state=present

    - name: add ceph user
      user:
        name: ceph-deploy
        home: /home/ceph-deploy
        shell: /bin/bash

    - name: create ceph .ssh directory
      file:
        path: /home/ceph-deploy/.ssh
        state: directory
        mode: 0700
        owner: ceph-deploy
        group: ceph-deploy

    - name: 'Ceph copy .ssh files'
      template:
        src: files/ceph/{{ item }}
        dest: /home/ceph-deploy/.ssh/{{ item }}
        mode: 0600
        owner: ceph-deploy
        group: ceph-deploy
      with_items: [config, id_rsa, id_rsa.pub, authorized_keys]
      register: ssh_files

    - name: 'CEPH: add ceph to sudoers'
      lineinfile:
        path: /etc/sudoers.d/ceph
        line: "ceph-deploy ALL = (root) NOPASSWD:ALL"
        mode: 0440
        create: yes

    - name: generate known_hosts file
      shell: |
        ssh-keyscan {{ item }} >> /home/ceph-deploy/.ssh/known_hosts
        ssh-keyscan $(dig +short {{ item }}) >> /home/ceph-deploy/.ssh/known_hosts
        chown ceph-deploy:ceph-deploy /home/ceph-deploy/.ssh/known_hosts
        chmod 600 /home/ceph-deploy/.ssh/known_hosts
      with_items: '{{ groups["ceph-all"] }}'
      when: ssh_files.changed

- hosts: '{{ groups["ceph-all"][0] }}'
  tasks:
    - name: create ceph my-cluster directory
      file:
        path: /home/ceph-deploy/my-cluster
        state: directory
        mode: 0700
        owner: ceph-deploy
        group: ceph-deploy

    - name: install new ceph cluster
      shell: ceph-deploy new {{ groups["ceph-all"]|join(' ') }}
      become: yes
      become_user: ceph-deploy
      args:
        chdir: /home/ceph-deploy/my-cluster
        creates: /home/ceph-deploy/my-cluster/ceph.conf
      register: ceph_new_cluster

    - name: install ceph
      shell: ceph-deploy install {{ groups["ceph-all"]|join(' ') }}
      become: yes
      become_user: ceph-deploy
      args: { chdir: /home/ceph-deploy/my-cluster }
      when: ceph_new_cluster.changed

    - name: install ceph
      shell: ceph-deploy mon create-initial
      become: yes
      become_user: ceph-deploy
      args: { chdir: /home/ceph-deploy/my-cluster }
      when: ceph_new_cluster.changed

    - name: install ceph
      shell: ceph-deploy admin {{ groups["ceph-all"]|join(' ') }}
      become: yes
      become_user: ceph-deploy
      args: { chdir: /home/ceph-deploy/my-cluster }
      when: ceph_new_cluster.changed

    - name: install ceph
      shell: ceph-deploy mgr create {{ groups['ceph-all'][0] }}
      become: yes
      become_user: ceph-deploy
      args: { chdir: /home/ceph-deploy/my-cluster }
      when: ceph_new_cluster.changed

    - name: install ceph
      shell: ceph-deploy osd create --data /dev/sda {{ item }}
      become: yes
      become_user: ceph-deploy
      args: { chdir: /home/ceph-deploy/my-cluster }
      with_items: '{{ groups["ceph-all"] }}'
      when: ceph_new_cluster.changed

    # K8S configuration
    - name: ceph - create kube pool
      shell: |
        ceph osd pool stats kube || ceph osd pool create kube 100 100
        ceph osd pool application enable kube rbd
      when: ceph_new_cluster.changed
