apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/rbd
parameters:
  monitors: {% for host in groups["ceph-all"] %}
{{  hostvars[host].ansible_host }}:6789{%- if not loop.last %}, {% endif -%}
{% endfor %}

  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: "kube-system"
  pool: kube
  userId: kube
  userSecretName: ceph-secret-kube
